# Site settings
title: NCICloud Pilot IRP Notes
email: sean.davis@nih.gov
description: > # this means to ignore newlines until "baseurl:"
   The NCI Clouds are an experiment in marrying valuable data with
   compute resources to enable cancer research. This site is a
   collection of notes on the CGC cloud pilots.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://teamcgc.github.io" # the base hostname & protocol for your site
twitter_username: @NCICloud
github_username:  teamcgc

# Build settings
markdown: kramdown
